package nl.bsoft.structural.facade;

public enum ServerState {
    NULL, BOOTED, CONFIGURED, INITED, INITEDCONTEXT, INITEDLISTENERS, READY, RELEASEDPROCESSES, DESTROY,
    DESTROYSYSTEMOBJECTS, DESTROYLISTENERS, DESTROYCONTEXT
}
